use_frameworks!

target 'ESPopupDialog_Example' do
  pod 'ESPopupDialog', :path => '../'

  target 'ESPopupDialog_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
